name: Publish npm packages ðŸ›°ï¸

on:
  push:
    branches:
      - main

permissions:
  packages: write
  contents: read

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - name: Check commit message
        id: check-commit
        run: |
          publish=false
          if [[ "${{ github.event.head_commit.message }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]
          then
            publish=true
          fi

          echo "publish=$skip" >> $GITHUB_OUTPUT

      - name: Get Node.JS version from package.json ðŸ‘€
        if: steps.check-commit.publish == 'true'
        id: get-versions
        run: echo "nodeVersion=$(jq -r .engines.node ./package.json)" >> $GITHUB_OUTPUT

      - name: Install pnpm ðŸ’¿
        if: steps.check-commit.publish == 'true'
        run: npm install -g pnpm@7

      - name: Setup Node ðŸŽ®
        if: steps.check-commit.publish == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.get-versions.outputs.nodeVersion }}
          cache: "pnpm"
          registry-url: "https://npm.pkg.github.com"
          scope: "@chainflip-io"

      - name: Install dependencies ðŸšš ðŸ“¦
        if: steps.check-commit.publish == 'true'
        run: pnpm install

      - name: Build
        if: steps.check-commit.publish == 'true'
        run: pnpm build
        working-directory: ./

      - name: Publish npm package ðŸ“¦
        if: steps.check-commit.publish == 'true'
        run: |
          pnpm publish
        working-directory: ./
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
