name: Test Swap Service

on:
  workflow_dispatch: {}
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - packages/swap-service/**
  push:
    branches:
      - main
    paths:
      - packages/swap-service/**

env:
  FORCE_COLOR: 1
  DB_NAME: "swap"
  DB_USER: "postgres"
  DB_PASS: "postgres"
  DB_PORT: "5432"
  PACKAGE: "swap-service"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV
          echo "DATABASE_URL=postgresql://$DB_USER:$DB_PASS@localhost:$DB_PORT/$DB_NAME?schema=public" >> $GITHUB_ENV

      - name: Docker Compose Action
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: ./packages/swap-service/docker-compose.yml

      - name: Install pnpm ðŸ’¿
        run: npm install -g pnpm@7

      - name: Setup Node ðŸŽ®
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Install dependencies ðŸšš ðŸ“¦
        run: pnpm --filter $PACKAGE install

      - name: migrate database
        run: pnpm --filter $PACKAGE exec pnpm prisma migrate dev

      - name: Run tests
        run: pnpm --filter $PACKAGE test:ci
