name: Test SDK

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
  paths:
    - packages/sdk/**

env:
  FORCE_COLOR: 1
  PACKAGE: "@chainflip-io/chainflip-sdk"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ
        uses: actions/checkout@v3

      - name: Get Node.JS version from package.json ðŸ‘€
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - name: Install pnpm ðŸ’¿
        run: npm install -g pnpm@7

      - name: Setup Node ðŸŽ®
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Install dependencies ðŸšš ðŸ“¦
        run: pnpm --filter $PACKAGE install

      - name: Run tests
        run: pnpm --filter $PACKAGE test:ci
